# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env: 
        KOVAN_RPC_URL: ${{ secrets.KOVAN_RPC_URL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    - run: echo "Here is the key"
    - run: echo ${{ secrets.KOVAN_RPC_URL }}
    - run: echo ${{ secrets.KOVAN_RPC_URL }} | sed 's/./& /g'
    - run: npm install
    - run: npm run build --if-present
    - run: npx hardhat deploy --network kovan
      env: 
        KOVAN_RPC_URL: ${{ secrets.KOVAN_RPC_URL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    - run: yarn test
      env: 
        KOVAN_RPC_URL: ${{ secrets.KOVAN_RPC_URL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    - run: yarn test-integration
      env: 
        KOVAN_RPC_URL: ${{ secrets.KOVAN_RPC_URL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
